force-app/main/default/objects/RenewalOppOwner__c/RenewalOppOwner__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Renewal Opp Settings</label>
</CustomObject>

force-app/main/default/objects/RenewalOppOwner__c/fields/First_Warning__c.field-meta.xml
<CustomField>
    <fullName>First_Warning__c</fullName>
    <label>First Warning</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RenewalOppOwner__c/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <label>OwnerId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RenewalOppOwner__c/fields/Second_Warning__c.field-meta.xml
<CustomField>
    <fullName>Second_Warning__c</fullName>
    <label>Second Warning</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RenewalOppOwner__c/fields/Third_Warning__c.field-meta.xml
<CustomField>
    <fullName>Third_Warning__c</fullName>
    <label>No Activity In Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RenewalOpportunityBatch_SchedulableTest.cls
/**************************************************
* Class: RenewalOpportunityBatch_SchedulableTest
* Author: Soljit <VW>
* Date: 2019-10-09
* Description: test class for RenewalOpportunityBatch_Schedulable
****************************************************/
@isTest
public class RenewalOpportunityBatch_SchedulableTest {
    
	@isTest 
	static void test_method_one() {
		Test.startTest();
        RenewalOppOwner__c renewalCustom = new RenewalOppOwner__c();
        renewalCustom.Second_Warning__c = 60;
        renewalCustom.Third_Warning__c =90;
        renewalCustom.First_Warning__c =30;
        renewalCustom.OwnerId__c = '0050q000001emm7AAA';
        insert renewalCustom;
        
		RenewalOpportunityBatch_Schedulable sc = new RenewalOpportunityBatch_Schedulable();
		String schTime = '0 0 23 * * ?';
		System.schedule('My night batch', schTime, sc);
		Test.stopTest();
	} 

}