force-app/main/default/objects/Account_Dups__c/Account_Dups__c.object-meta.xml
<CustomObject>
    <label>Duplicate Account</label>
    <nameField>
        <displayFormat>DUP ACC-{000000}</displayFormat>
        <label>Account Dups Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Dups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Dups__c/fields/Duplicate_Account__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Duplicate Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Accounts_Dups1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <label>Last Activity Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Master_Account__c.field-meta.xml
<CustomField>
    <fullName>Master_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winning Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Dups (Master Account)</relationshipLabel>
    <relationshipName>Accounts_Dups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Number_of_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Opportunity__c</fullName>
    <label>Number of Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DuplicateAccountTableControllerTest.cls
@IsTest
public class DuplicateAccountTableControllerTest {
 @testSetup 
    static void Createrecords(){
        
        List<Account_Dups__c> dupList = new List<Account_Dups__c>();
         Account_Dups__c dupRec = new Account_Dups__c(); 
        dupRec.Master_Account__c = null;
        dupRec.Duplicate_Account__c = null;
        dupRec.Last_Activity_Date__c = System.now();
        //dupRec.Fuzzy_Match__c = true;
        dupRec.Number_of_Opportunity__c = 5;  
        dupList.add(dupRec);
        
        insert dupList;
    }
    @isTest 
    static void DuplicateAccountTableMethod(){
        List<Account_Dups__c> dupsList = [SELECT Id, Name,Master_Account__c,Master_Account__r.id, Duplicate_Account__r.Name, Duplicate_Account__c, Number_of_Opportunity__c FROM Account_Dups__c Limit 1]; 
        Map<String, List<Account_Dups__c>> RecdataMap = new Map<String, List<Account_Dups__c>>();
        for(Account_Dups__c dups : dupsList){
           RecdataMap.put(dups.Master_Account__c, dupsList);
        }
        Test.startTest();
       DuplicateAccountTableController extension = new DuplicateAccountTableController();
       extension.dataMap = RecdataMap;
        Test.stopTest();
        
        System.assertEquals(1, [select count(id) from Account_Dups__c].size());
    }
}