force-app/main/default/objects/Account_Dups__c/Account_Dups__c.object-meta.xml
<CustomObject>
    <label>Duplicate Account</label>
    <nameField>
        <displayFormat>DUP ACC-{000000}</displayFormat>
        <label>Account Dups Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Dups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Dups__c/fields/Duplicate_Account__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Duplicate Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Accounts_Dups1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <label>Last Activity Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Master_Account__c.field-meta.xml
<CustomField>
    <fullName>Master_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winning Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Dups (Master Account)</relationshipLabel>
    <relationshipName>Accounts_Dups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Number_of_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Opportunity__c</fullName>
    <label>Number of Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountDupes.cls
public with sharing class AccountDupes
{

    public List<DupsInfoWrapper> DupesWrapper {get; set;}    
    //added for paginnation
    public List<List<DupsInfoWrapper>> listofDupesWrapper {get; set;}
    
    public AccountDupes()
    {
  DupesWrapper = new List<DupsInfoWrapper>();
  listofDupesWrapper = new List<List<DupsInfoWrapper>>();
        getDups();
    } 
     
    public void getDups()   
    {
        for(Account_Dups__c s:[Select id, Name, Duplicate_Account__r.Name,Master_Account__r.Name, Number_of_Opportunity__c, Last_Activity_Date__c FROM Account_Dups__c])
        {            
            DupesWrapper.add(new DupsInfoWrapper(s)); 
            if(DupesWrapper.size() == 999)
   {
    listofDupesWrapper.add(DupesWrapper);
     DupesWrapper= new List<DupsInfoWrapper>();
            }                
        } 
        if(DupesWrapper.size() != 0){
   listofDupesWrapper.add(DupesWrapper);
     }   
        
    }
    
 //Wrapper class
    public class DupsInfoWrapper
    {
        public Account_Dups__c dObj{get;set;}
        public Boolean checked {get;set;}
        public DupsInfoWrapper(Account_Dups__c dup)
        {
            dObj = dup;  
            checked=false;  
        } 
    }
}