force-app/main/default/objects/Account_Dups__c/Account_Dups__c.object-meta.xml
<CustomObject>
    <label>Duplicate Account</label>
    <nameField>
        <displayFormat>DUP ACC-{000000}</displayFormat>
        <label>Account Dups Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Dups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Dups__c/fields/Duplicate_Account__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Duplicate Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Accounts_Dups1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <label>Last Activity Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Master_Account__c.field-meta.xml
<CustomField>
    <fullName>Master_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winning Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Dups (Master Account)</relationshipLabel>
    <relationshipName>Accounts_Dups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Number_of_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Opportunity__c</fullName>
    <label>Number of Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MergeAccountTest.cls
@IsTest
public class MergeAccountTest {
@TestSetup
    static void createRecord(){
        id recTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Test';
        acc.RecordTypeId = recTypeId;
        insert acc;
        
        Account acc2 = new Account();
        acc2.Name  = 'Test';
        acc2.RecordTypeId = recTypeId;
        insert acc2;
        
        List<Account_Dups__c> dupList = new List<Account_Dups__c>();
         Account_Dups__c dupRec = new Account_Dups__c(); 
        dupRec.Master_Account__c = acc.id;
        dupRec.Duplicate_Account__c = acc2.Id;
        dupRec.Last_Activity_Date__c = System.now();
        dupRec.Number_of_Opportunity__c = 2;  
        dupList.add(dupRec);
        
        insert dupList;
        
    }
    @isTest
    static void TestMerge(){
        Account_Dups__c dups = [select id,Master_Account__c,Duplicate_Account__c from Account_Dups__c limit 1];
        test.startTest();
        MergeAccount.MergeAccountS(dups.id);
        system.assertNotEquals(null, dups.Id);
            test.stopTest();
    }
   
}