force-app/main/default/objects/Account_Dups__c/Account_Dups__c.object-meta.xml
<CustomObject>
    <label>Duplicate Account</label>
    <nameField>
        <displayFormat>DUP ACC-{000000}</displayFormat>
        <label>Account Dups Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Dups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Dups__c/fields/Duplicate_Account__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Duplicate Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Accounts_Dups1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Master_Account__c.field-meta.xml
<CustomField>
    <fullName>Master_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winning Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Dups (Master Account)</relationshipLabel>
    <relationshipName>Accounts_Dups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MergeDuplicateAccountBatch.cls
global class MergeDuplicateAccountBatch implements Database.Batchable<sObject>,Database.Stateful{
    global String query;
    global MergeDuplicateAccountBatch(){
        query = 'SELECT Id,Name,Duplicate_Account__c,Master_Account__c FROM Account_Dups__c';
    }
    // Batch Start Method
    global Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('query = '+query);
        return Database.getQueryLocator(query);
    }
    
    //Batch Execute Method
    global void execute(Database.BatchableContext BC, List<Account_Dups__c> duplicateData){
        System.debug('duplicateData^^' + duplicateData.size());
        if(duplicateData.size() > 0){
            Map<String,List<Id>> parentWithDuplicateMap = new Map<String,List<Id>>();
            for(Account_Dups__c accDup : duplicateData){
                if(!parentWithDuplicateMap.containsKey(accDup.Master_Account__c)){
                    parentWithDuplicateMap.put(accDup.Master_Account__c,new List<Id>());
                }
                parentWithDuplicateMap.get(accDup.Master_Account__c).add(accDup.Duplicate_Account__c);
            }
            System.debug('parentWithDuplicateMap^^' + parentWithDuplicateMap.size());
            if(parentWithDuplicateMap.size() > 0){
                for(String masterId : parentWithDuplicateMap.keySet()){
                    MergeUtility.mergeData(masterId,parentWithDuplicateMap.get(masterId));
                }
            }
        }
    }
    
    // Finish Method
    global void finish(Database.BatchableContext BC){
        
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
                            JobItemsProcessed,
                            TotalJobItems
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];
        System.debug('#### job^^' + job);
        System.debug('#### MergeDuplicateAccountBatch Finished.');
    }
}