force-app/main/default/objects/Account_Dups__c/Account_Dups__c.object-meta.xml
<CustomObject>
    <label>Duplicate Account</label>
    <nameField>
        <displayFormat>DUP ACC-{000000}</displayFormat>
        <label>Account Dups Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Dups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Dups__c/fields/Master_Account__c.field-meta.xml
<CustomField>
    <fullName>Master_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winning Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Dups (Master Account)</relationshipLabel>
    <relationshipName>Accounts_Dups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddDuplicateAccountsController.cls
public class AddDuplicateAccountsController {
    @AuraEnabled
    public static Result createDuplicateAccounts(String winningAccount, String duplicateAccountData){
        Account_Dups__c winningAccountRecord = (Account_Dups__c)JSON.deserialize(winningAccount, Account_Dups__c.class);
        List<Account_Dups__c> duplicateDataList = (List<Account_Dups__c>)JSON.deserialize(duplicateAccountData, List<Account_Dups__c>.class);
        Result res = new Result();
        
        System.debug('winningAccountRecord^^' + winningAccountRecord);
        System.debug('duplicateDataList^^' + duplicateDataList.size());
        
        for(Account_Dups__c dupAccounts : duplicateDataList){
            dupAccounts.Master_Account__c = winningAccountRecord.Master_Account__c;
        }
        
        try{
            if(duplicateDataList.size() > 0){
                INSERT duplicateDataList;
                res.status = 'Success';
                res.message = 'Duplicate accounts inserted successfully.';
            }
        }catch(Exception ex){
            System.debug('exception occured on insertion^^' + ex.getMessage());
            res.status = 'Error';
            res.message = String.valueOf(ex);
        }
        return res;
    }
    public class Result{
        @AuraEnabled public String status {get;set;}
        @AuraEnabled public String message {get;set;}
    }   
}