force-app/main/default/objects/Account_Dups__c/Account_Dups__c.object-meta.xml
<CustomObject>
    <label>Duplicate Account</label>
    <nameField>
        <displayFormat>DUP ACC-{000000}</displayFormat>
        <label>Account Dups Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Dups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Dups__c/fields/Duplicate_Account__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Duplicate Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Accounts_Dups1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Master_Account__c.field-meta.xml
<CustomField>
    <fullName>Master_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winning Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Dups (Master Account)</relationshipLabel>
    <relationshipName>Accounts_Dups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MergeDuplicateAccounts.cls
global class MergeDuplicateAccounts implements Database.Batchable<sObject>, Database.Stateful {
    
    global String query;
    global String accId;
    global MergeDuplicateAccounts(){
        //accId = 'a3T030000004jJPEAY';
        query = 'SELECT Id, Master_Account__c, Duplicate_Account__c FROM Account_Dups__c';
    }    
    global Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('query = '+query);
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Account_Dups__c> scope) {
        system.debug('scope'+scope);
        Map<Id,List<Account_Dups__c>> accATLMap = new Map<Id,List<Account_Dups__c>>();
        for(Account_Dups__c adc: scope){
            if (accATLMap.get(adc.Master_Account__c) == null)
            {
                // instantiate a new list
                accATLMap.put(adc.Master_Account__c, new List <Account_Dups__c> ());
            }
            // add the element to the list
            accATLMap.get(adc.Master_Account__c).add(adc);
        }        
        System.debug('accATLMap'+accATLMap);
    }
    global void finish(Database.BatchableContext BC) {
        
    }
}