force-app/main/default/objects/Account_Dups__c/Account_Dups__c.object-meta.xml
<CustomObject>
    <label>Duplicate Account</label>
    <nameField>
        <displayFormat>DUP ACC-{000000}</displayFormat>
        <label>Account Dups Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Dups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Dups__c/fields/Duplicate_Account__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Duplicate Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Accounts_Dups1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date__c</fullName>
    <label>Last Activity Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Master_Account__c.field-meta.xml
<CustomField>
    <fullName>Master_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winning Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Dups (Master Account)</relationshipLabel>
    <relationshipName>Accounts_Dups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Dups__c/fields/Number_of_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Opportunity__c</fullName>
    <label>Number of Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AddDuplicateAccountsControllerTest.cls
@isTest
private class AddDuplicateAccountsControllerTest {
	@testSetup
    static void createData(){
        Account acc = new Account();
        acc.Name = 'Test';
        acc.Is_Processed__c = false;
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Account').getRecordTypeId();
        insert acc;
        
        Account acc2 = new Account();
        acc2.Name = 'Test2';
        acc2.Is_Processed__c = false;
        acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Account').getRecordTypeId();
        insert acc2;
        
        
        Account_Dups__c acDup = new Account_Dups__c();
        acDup.Master_Account__c = acc.id;
        acDup.Duplicate_Account__c = acc2.id;
        acDup.Number_of_Opportunity__c = 5;
        acDup.Last_Activity_Date__c = system.now();
        insert acDup;
       
    }
    
    @isTest
    static void testcreateDuplicateAccounts(){
    	Account_Dups__c  dupAcc1 = [SELECT Id,Name FROM Account_Dups__c  LIMIT 1];
        String strJSON = JSON.serialize(dupAcc1);
        Account_Dups__c  dupAcc2 = [SELECT Id,Name FROM Account_Dups__c LIMIT 1];
        String strJSON2 = JSON.serialize(new List<Account_Dups__c>{dupAcc1, dupAcc2});
        system.assertNotEquals(null, strJSON2);
        system.assertNotEquals(null, strJSON);
        Test.startTest();
        AddDuplicateAccountsController.createDuplicateAccounts(strJSON,strJSON2);
        Test.stopTest();
    }
}