force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/CSV_INVOICE_DATA_TEMP__c.object-meta.xml
<CustomObject>
    <label>CSV INVOICE DATA TEMP</label>
    <nameField>
        <displayFormat>CSV-{0000}</displayFormat>
        <label>CSV INVOICE DATA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSV INVOICE DATA TEMP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Type__c</fullName>
    <label>Calculation_Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <label>Contract_End_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/Contract_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_ID__c</fullName>
    <label>Contract_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <label>Contract_Start_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/Contract_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term_Months__c</fullName>
    <label>Contract_Term_Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/Formula_for_match_with_Contract_c__c.field-meta.xml
<CustomField>
    <fullName>Formula_for_match_with_Contract_c__c</fullName>
    <formula>IF(Commodity__c = &quot;Gas&quot;,&quot;Gas&quot;,IF(Commodity__c = &quot;Power&quot;,&quot;Electricity&quot;,&quot; &quot;))&amp; &quot;-&quot;&amp;
text(Contract_Term_Months__c) &amp; &quot;-&quot;&amp;
TEXT(DAY(Contract_Start_Date__c))+ &quot;-&quot; +TEXT(MONTH(Contract_Start_Date__c))+ &quot;-&quot; +TEXT(YEAR(Contract_Start_Date__c))
&amp; &quot;-&quot;&amp;
TEXT(DAY(Contract_End_Date__c))+ &quot;-&quot; +TEXT(MONTH(Contract_End_Date__c))+ &quot;-&quot; +TEXT(YEAR(Contract_End_Date__c))
&amp; &quot;-&quot; &amp;
Customer_Name__c
&amp; &quot;-&quot; &amp;
LDC_Account_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Formula_for_match_with_Contract__c</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/LDC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>LDC_Account_Number__c</fullName>
    <label>LDC_Account_Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/MatchedContract__c.field-meta.xml
<CustomField>
    <fullName>MatchedContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MatchedContract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>CSV INVOICE DATA TEMP (MatchedContract)</relationshipLabel>
    <relationshipName>CSV_INVOICE_DATA_TEMP1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/Matching_Contract__c.field-meta.xml
<CustomField>
    <fullName>Matching_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Matching Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>CSV INVOICE DATA</relationshipLabel>
    <relationshipName>CSV_INVOICE_DATA_TEMP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>CSV INVOICE DATA</relationshipLabel>
    <relationshipName>CSV_INVOICE_DATA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Site__c/Opportunity_Site__c.object-meta.xml
<CustomObject>
    <label>Opportunity Site</label>
    <nameField>
        <displayFormat>OppSite-{00000000}</displayFormat>
        <label>Opportunity Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Site__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Site</relationshipLabel>
    <relationshipName>Opportunity_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Site__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Opportunity Site</relationshipLabel>
    <relationshipName>Opportunity_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Location Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Address</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceEntryProcessBatch.cls
public class InvoiceEntryProcessBatch implements Database.Batchable<sObject>{
    
    public String Query;
    public string recordId ;
    public InvoiceEntryProcessBatch(){
        Query= 'SELECT id,LDC_Account_Number__c,Reason__c,MatchedContract__c,Formula_for_match_with_Contract_c__c,Contract_ID__c,Calculation_Type__c,Customer_Name__c,Contract_Start_Date__c,Contract_End_Date__c,Contract_Term_Months__c,Commodity__c FROM CSV_INVOICE_DATA_TEMP__c WHERE Matching_Contract__c != null';
    }
    public InvoiceEntryProcessBatch(string recId){
        recordId = recId;
        Query= 'SELECT id,LDC_Account_Number__c,Reason__c,MatchedContract__c,Formula_for_match_with_Contract_c__c,Contract_ID__c,Calculation_Type__c,Customer_Name__c,Contract_Start_Date__c,Contract_End_Date__c,Contract_Term_Months__c,Commodity__c FROM CSV_INVOICE_DATA_TEMP__c WHERE id =: recordId';
    }
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<CSV_INVOICE_DATA_TEMP__c> EntryList){
        set<string> SiteIdSet = new set<string>();
        For(CSV_INVOICE_DATA_TEMP__c invoice: EntryList){
            SiteIdSet.add(invoice.LDC_Account_Number__c);
        }
        system.debug('SiteIdSet ::'+SiteIdSet);
        List<Site__c> SiteList = [select id,Name,Account__c,Account__r.ParentId,Account__r.Parent.Name from Site__c where Name IN: SiteIdSet];
        set<id> ParentAccIdSet = new set<id>();
        For(Site__c site: SiteList){
            ParentAccIdSet.add(site.Account__r.ParentId);
        }
        system.debug('ParentAccIdSet ::'+ParentAccIdSet);
        string AccName;
        //List<string> oppList = new List<string>();
        For(Opportunity opp: [select id,Name,AccountId,Account.Name from Opportunity 
                              where AccountId IN: ParentAccIdSet]){
                                  AccName = opp.Account.Name;
                                  //        oppList.add(opp.id);
                              }
        //system.debug('oppList ::'+oppList);
        system.debug('AccName ::'+AccName);
        Map<id,string> SiteMap = new Map<id,string>();
        List<string> oppIds = new List<string>();
        For(Opportunity_Site__c oppSite: [SELECT Id, Name, Site__c,Site__r.Name, Opportunity__c,Opportunity__r.Main_Opportunity__c FROM Opportunity_Site__c WHERE Site__r.Name IN: SiteIdSet]){
            if(oppSite.Opportunity__r.Main_Opportunity__c == null){
                SiteMap.put(oppSite.Opportunity__c,oppSite.Site__r.Name);
            }else{
                SiteMap.put(oppSite.Opportunity__r.Main_Opportunity__c,oppSite.Site__r.Name);
            }
        }
        system.debug('SiteMap ::'+SiteMap);
        for(id oppid: SiteMap.keyset()){
            oppIds.add(oppid);
        }
        system.debug('oppIds ::'+oppIds);
        //  Map<string,List<Contract>> ContractMap = new Map<string,List<Contract>>();
        List<Contract> contrList = new List<Contract>();
        For(Contract Contr: [SELECT Id,EndDate,StartDate,ContractTerm,Account.Name,SBQQ__Opportunity__c,SBQQ__Opportunity__r.Commodity_Type__c,AccountId FROM Contract 
                             WHERE SBQQ__Opportunity__c IN: oppIds]){
                                 //        if(!ContractMap.containsKey(Contr.Account.Name)){
                                 //           ContractMap.put(Contr.Account.Name, new List<Contract>());
                                 //       }
                                 //       ContractMap.get(Contr.Account.Name).add(Contr);
                                 contrList.add(Contr);
                             }
        system.debug('contrList ::'+contrList);
        Map<string,string> commodityMap = new Map<string,string>();
        commodityMap.put('Power','Electricity');
        commodityMap.put('Gas','Gas');
        string ReasonForNotMatch = '';
        List<CSV_INVOICE_DATA_TEMP__c> InvoiceList = new List<CSV_INVOICE_DATA_TEMP__c>();
        /*For(CSV_INVOICE_DATA_TEMP__c invoice: EntryList){
if(AccName.containsAny(invoice.Customer_Name__c)){
system.debug('yes');
if(ContractMap.containsKey(AccName)){
For(Contract contr: ContractMap.get(AccName)){
if(SiteMap.containsKey(contr.SBQQ__Opportunity__c)){
if(contr.SBQQ__Opportunity__r.Commodity_Type__c == commodityMap.get(invoice.Commodity__c)){
if(contr.EndDate == invoice.Contract_End_Date__c){
if(contr.StartDate != invoice.Contract_Start_Date__c){
ReasonForNotMatch += 'StartDateError ,';
}
if(contr.ContractTerm != invoice.Contract_Term_Months__c){
ReasonForNotMatch += 'TermError ,';
} 
if(contr.StartDate == invoice.Contract_Start_Date__c && contr.EndDate == invoice.Contract_End_Date__c &&
contr.ContractTerm == invoice.Contract_Term_Months__c && contr.SBQQ__Opportunity__r.Commodity_Type__c == commodityMap.get(invoice.Commodity__c)){
ReasonForNotMatch += 'RightRecord';
}
invoice.Matching_Contract__c = contr.id;
}   
}

}
}
}
}
ReasonForNotMatch = ReasonForNotMatch.removeEnd(',');
system.debug('ReasonForNotMatch ::'+ReasonForNotMatch);
invoice.Reason__c = ReasonForNotMatch;
InvoiceList.add(invoice);
}*/
        For(CSV_INVOICE_DATA_TEMP__c invoice: EntryList){
            if(AccName.containsAny(invoice.Customer_Name__c)){
                //if(ContractMap.containsKey(AccName)){
                For(Contract contr: contrList){
                    if(SiteMap.containsKey(contr.SBQQ__Opportunity__c)){
                        if(contr.SBQQ__Opportunity__r.Commodity_Type__c == commodityMap.get(invoice.Commodity__c)){
                            if(contr.EndDate == invoice.Contract_End_Date__c){
                                system.debug('contains-5');
                                if(contr.StartDate != invoice.Contract_Start_Date__c){
                                    ReasonForNotMatch += 'StartDateError ,';
                                }
                                if(contr.ContractTerm != invoice.Contract_Term_Months__c){
                                    ReasonForNotMatch += 'TermError ,';
                                } 
                                if(contr.StartDate == invoice.Contract_Start_Date__c && contr.EndDate == invoice.Contract_End_Date__c &&
                                   contr.ContractTerm == invoice.Contract_Term_Months__c && contr.SBQQ__Opportunity__r.Commodity_Type__c == commodityMap.get(invoice.Commodity__c)){
                                       ReasonForNotMatch += 'RightRecord';
                                   }
                                invoice.MatchedContract__c = contr.id;
                            }   
                        }
                        
                        // }
                    }
                }
            }
            ReasonForNotMatch = ReasonForNotMatch.removeEnd(',');
            system.debug('ReasonForNotMatch ::'+ReasonForNotMatch);
            invoice.Reason__c = ReasonForNotMatch;
            InvoiceList.add(invoice);
        }
        system.debug('InvoiceList ::'+InvoiceList);
        if(InvoiceList.size()>0){
            update InvoiceList;
        }
    }
    
    public void finish(Database.BatchableContext BC){
    }
}