force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/CSV_INVOICE_DATA_TEMP__c.object-meta.xml
<CustomObject>
    <label>CSV INVOICE DATA TEMP</label>
    <nameField>
        <displayFormat>CSV-{0000}</displayFormat>
        <label>CSV INVOICE DATA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSV INVOICE DATA TEMP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Type__c</fullName>
    <label>Calculation_Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/Contract_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_ID__c</fullName>
    <label>Contract_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/Formula_for_match_with_Contract_c__c.field-meta.xml
<CustomField>
    <fullName>Formula_for_match_with_Contract_c__c</fullName>
    <formula>IF(Commodity__c = &quot;Gas&quot;,&quot;Gas&quot;,IF(Commodity__c = &quot;Power&quot;,&quot;Electricity&quot;,&quot; &quot;))&amp; &quot;-&quot;&amp;
text(Contract_Term_Months__c) &amp; &quot;-&quot;&amp;
TEXT(DAY(Contract_Start_Date__c))+ &quot;-&quot; +TEXT(MONTH(Contract_Start_Date__c))+ &quot;-&quot; +TEXT(YEAR(Contract_Start_Date__c))
&amp; &quot;-&quot;&amp;
TEXT(DAY(Contract_End_Date__c))+ &quot;-&quot; +TEXT(MONTH(Contract_End_Date__c))+ &quot;-&quot; +TEXT(YEAR(Contract_End_Date__c))
&amp; &quot;-&quot; &amp;
Customer_Name__c
&amp; &quot;-&quot; &amp;
LDC_Account_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Formula_for_match_with_Contract__c</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/MatchedContract__c.field-meta.xml
<CustomField>
    <fullName>MatchedContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MatchedContract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>CSV INVOICE DATA TEMP (MatchedContract)</relationshipLabel>
    <relationshipName>CSV_INVOICE_DATA_TEMP1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CSV_INVOICE_DATA_TEMP__c/fields/Matching_Contract__c.field-meta.xml
<CustomField>
    <fullName>Matching_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Matching Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>CSV INVOICE DATA</relationshipLabel>
    <relationshipName>CSV_INVOICE_DATA_TEMP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceEntryController.cls
public class InvoiceEntryController {
    
    @AuraEnabled
    public static List<sObject> getData(string objName){
        system.debug('objName ::'+objName);
        string query = 'SELECT id,MatchedContract__c,Formula_for_match_with_Contract_c__c,Contract_ID__c,Calculation_Type__c,Reason__c FROM '+objName+' WHERE Matching_Contract__c != null';
        List<sObject> DataList = database.query(query);
        system.debug('DataList ::'+DataList);
        return DataList;
    }
    @AuraEnabled
    public static string ProcessEntry(List<string> SelectedRec){
        system.debug('SelectedRec ::'+SelectedRec);
        string message;
        if(SelectedRec ==  null || SelectedRec.size() == 0){
            message = 'Please select atleast one record!';
            return message;
        }
        set<id> ContractId = new set<id>();
        Map<id,CSV_INVOICE_DATA_TEMP__c> InvoiceMap = new  Map<id,CSV_INVOICE_DATA_TEMP__c>();
        Map<string,string> paymentTypeMap = new Map<string,string>();
        paymentTypeMap.put('50/50 On Flow', '50% Upfront on flow and 50% Residual - Monthly');
        paymentTypeMap.put('50/50 Upfront', '50% Upfront on flow and 50% Residual - Monthly');
        paymentTypeMap.put('On Flow', '100% Residual - Monthly');
        
        List<CSV_INVOICE_DATA_TEMP__c> InvoiceList = [SELECT id,MatchedContract__c,Formula_for_match_with_Contract_c__c,Contract_ID__c,Calculation_Type__c,Reason__c FROM CSV_INVOICE_DATA_TEMP__c WHERE id IN: SelectedRec];
        For(CSV_INVOICE_DATA_TEMP__c Invoice: InvoiceList){
            ContractId.add(Invoice.MatchedContract__c);
            InvoiceMap.put(Invoice.MatchedContract__c, Invoice);
        }
        system.debug('ContractId ::'+ContractId);
        system.debug('InvoiceMap ::'+InvoiceMap);
        List<Contract> contrList = new List<Contract>();
        For(Contract contr: [select id,name,supplier_s_contract_ID__c,Payment_Terms__c from Contract where id IN: ContractId]){
            if(InvoiceMap.containsKey(contr.Id)){
                CSV_INVOICE_DATA_TEMP__c invEntry =  InvoiceMap.get(contr.Id);  
                if(contr.supplier_s_contract_ID__c == null || contr.supplier_s_contract_ID__c == ''){
                    contr.supplier_s_contract_ID__c = invEntry.Contract_ID__c;
                }
                if(contr.Payment_Terms__c == null || contr.Payment_Terms__c == ''){
                    contr.Payment_Terms__c = paymentTypeMap.get(invEntry.Calculation_Type__c);
                }
                contrList.add(contr);
            }
        }
        system.debug('contrList ::'+contrList);
        List<CSV_INVOICE_DATA_TEMP__c> CsvINvoiceList = new List<CSV_INVOICE_DATA_TEMP__c>();
        if(contrList.size()>0){
            try{
                update contrList;
                message = 'Record Processed successfully!';
                
                for(Contract cont: contrList){
                    if(InvoiceMap.containsKey(cont.Id)){
                        CSV_INVOICE_DATA_TEMP__c invEntry =  InvoiceMap.get(cont.Id);
                        invEntry.Matching_Contract__c = null;
                        CsvINvoiceList.add(invEntry);
                    }
                }
            }catch(Exception ex){
                message = ex.getMessage();
            }
            if(CsvINvoiceList.size()>0){
                try{
                    update CsvINvoiceList;
                }catch(Exception ex){
                    message = ex.getMessage();
                }
            }
        }
        return message;
    }
}