force-app/main/default/objects/Residential_Commission__c/Residential_Commission__c.object-meta.xml
<CustomObject>
    <label>Residential Commission</label>
    <nameField>
        <displayFormat>RC-{000000000}</displayFormat>
        <label>Residential Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residential Commission</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Residential_Commission__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Residential_Commission__c/fields/Residential_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Residential_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Opportunity</label>
    <referenceTo>Residential_Opportunity__c</referenceTo>
    <relationshipLabel>Residential Commission</relationshipLabel>
    <relationshipName>Residential_Commission</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Residential_Commission_Hierarchy__c/Residential_Commission_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Residential Commission Hierarchy</label>
    <nameField>
        <label>Residential Commission Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Commission hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Residential_Commission_Hierarchy__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residential Commission hierarchies (Closer)</relationshipLabel>
    <relationshipName>Residential_Commission_hierarchiesF3PS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Residential_Commission_Hierarchy__c/fields/Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Effective_From__c</fullName>
    <label>Effective From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Residential_Commission_Hierarchy__c/fields/Level1__c.field-meta.xml
<CustomField>
    <fullName>Level1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residential Commission hierarchies</relationshipLabel>
    <relationshipName>Residential_Commission_hierarchies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Residential_Commission_Hierarchy__c/fields/Level2__c.field-meta.xml
<CustomField>
    <fullName>Level2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residential Commission hierarchies (Level 2)</relationshipLabel>
    <relationshipName>Residential_Commission_hierarchies1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Residential_Commission_Hierarchy__c/fields/Level3__c.field-meta.xml
<CustomField>
    <fullName>Level3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 3</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residential Commission hierarchies (Level 3)</relationshipLabel>
    <relationshipName>Residential_Commission_hierarchies2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Residential_Commission_Hierarchy__c/fields/Level4__c.field-meta.xml
<CustomField>
    <fullName>Level4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 4</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residential Commission hierarchies (Level 4)</relationshipLabel>
    <relationshipName>Residential_Commission_hierarchies3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Residential_Commission_Hierarchy__c/fields/Level5__c.field-meta.xml
<CustomField>
    <fullName>Level5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 5</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residential Commission hierarchies (Level 5)</relationshipLabel>
    <relationshipName>Residential_Commission_hierarchies4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Residential_Opportunity__c/Residential_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Residential Opportunity</label>
    <nameField>
        <label>Residential Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Opportunity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Residential_Opportunity__c/fields/Cancelled_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Date__c</fullName>
    <description>This field hold the date on that Residential Opportunity cancelled.</description>
    <inlineHelpText>Residential Opportunity cancelled date.</inlineHelpText>
    <label>Cancelled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Residential_Opportunity__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <label>Commodity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Electricity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Residential_Opportunity__c/fields/ContractSource__c.field-meta.xml
<CustomField>
    <fullName>ContractSource__c</fullName>
    <label>Contract Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Residential_Opportunity__c/fields/ECC__c.field-meta.xml
<CustomField>
    <fullName>ECC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ECC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Residential_Opportunity__c/fields/ResidentialCommissionConfigure__c.field-meta.xml
<CustomField>
    <fullName>ResidentialCommissionConfigure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Commission Configure</label>
    <referenceTo>ResidentialCommissionConfigure__c</referenceTo>
    <relationshipLabel>Residential Opportunity</relationshipLabel>
    <relationshipName>Residential_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Residential_Opportunity__c/fields/StageName__c.field-meta.xml
<CustomField>
    <fullName>StageName__c</fullName>
    <label>StageName</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Needs Analysis</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/ResidentialCommissionConfigure__c.object-meta.xml
<CustomObject>
    <label>Residential Commission Configure</label>
    <nameField>
        <label>Residential Commission Configure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Commissions Configure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Clawbacktime__c.field-meta.xml
<CustomField>
    <fullName>Clawbacktime__c</fullName>
    <defaultValue>90</defaultValue>
    <label>Clawback time (in days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <label>Closer Commission Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Contractsource__c.field-meta.xml
<CustomField>
    <fullName>Contractsource__c</fullName>
    <label>Contract Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/ECC__c.field-meta.xml
<CustomField>
    <fullName>ECC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ECC (Yes or No)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/EffectiveFrom__c.field-meta.xml
<CustomField>
    <fullName>EffectiveFrom__c</fullName>
    <label>Effective From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Flat_Fee_Paid_To_DNE__c.field-meta.xml
<CustomField>
    <fullName>Flat_Fee_Paid_To_DNE__c</fullName>
    <description>Total amount that DNE got as commission on Residual Opportunity.</description>
    <inlineHelpText>Total amount that DNE got as commission on Residual Opportunity.</inlineHelpText>
    <label>Flat Fee Paid To DNE</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Level1__c.field-meta.xml
<CustomField>
    <fullName>Level1__c</fullName>
    <label>Level 1 Commission Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Level2__c.field-meta.xml
<CustomField>
    <fullName>Level2__c</fullName>
    <label>Level 2 Commission Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Level3__c.field-meta.xml
<CustomField>
    <fullName>Level3__c</fullName>
    <label>Level 3 Commission Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Level4__c.field-meta.xml
<CustomField>
    <fullName>Level4__c</fullName>
    <label>Level 4 Commission Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Level5__c.field-meta.xml
<CustomField>
    <fullName>Level5__c</fullName>
    <label>Level 5 Commission Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/ProvinceorState__c.field-meta.xml
<CustomField>
    <fullName>ProvinceorState__c</fullName>
    <label>Province or State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Residential Commissions Configure</relationshipLabel>
    <relationshipName>Residential_Commissions_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResidentialOppotunityHandlerTest.cls
/*************************************************************
* Class: ResidentialOppotunityHandlerTest
* Author: Soljit <VW>
* Date: 2019-12-2
* Description: Residentail Opportunity trigger test class
**************************************************************/
@isTest
private class ResidentialOppotunityHandlerTest {
    @testSetup
    public static void createData()
    {
            Date d1 = date.today();
            Date EffectiveFrom = d1.addDays(-2);
        
        //--------CREATING THE ACCOUNT--------------
        Account AccountRecord = new Account();
        AccountRecord.Name = 'Test Account Data';
        AccountRecord.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Supplier').getRecordTypeId();//'0120q000000O2HIAA0';
        Insert AccountRecord;
        
        //--------CREATING THE CONTACT--------------
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName =  'Contact';
        con.AccountId = AccountRecord.Id; 
        Insert con;
      
        
        //--------CREATING THE CONTACT CLOSER--------------
        Contact ContactRecord = new Contact();
        ContactRecord.FirstName = 'Test';
        ContactRecord.LastName = 'Data';
        ContactRecord.AccountId = AccountRecord.Id;
        Insert ContactRecord;
        
        //--------CREATING THE CONTACT RECEIVER 1--------------
        Contact ContactRecord1 = new Contact();
        ContactRecord1.FirstName = 'Test';
        ContactRecord1.LastName = 'Data 01';
        ContactRecord1.AccountId = AccountRecord.Id;
        Insert ContactRecord1;
        
        ////--------CREATING THE CONTACT RECEIVER 2--------------
        Contact ContactRecord2 = new Contact();
        ContactRecord2.FirstName = 'Test';
        ContactRecord2.LastName = 'Data 02';
        ContactRecord2.AccountId = AccountRecord.Id;
        Insert ContactRecord2;
        
        //--------CREATING THE CONTACT RECEIVER 3--------------
        Contact ContactRecord3 = new Contact();
        ContactRecord3.FirstName = 'Test';
        ContactRecord3.LastName = 'Data 03';
        ContactRecord3.AccountId = AccountRecord.Id;
        Insert ContactRecord3;
        
        //--------CREATING THE CONTACT RECEIVER 4--------------
        Contact ContactRecord4 = new Contact();
        ContactRecord4.FirstName = 'Test';
        ContactRecord4.LastName = 'Data 04';
        ContactRecord4.AccountId = AccountRecord.Id;
        Insert ContactRecord4;
        
        //--------CREATING THE CONTACT RECEIVER 5--------------
        Contact ContactRecord5 = new Contact();
        ContactRecord5.FirstName = 'Test';
        ContactRecord5.LastName = 'Data 05';
        ContactRecord5.AccountId = AccountRecord.Id;
        Insert ContactRecord5;
        
        //--------CREATING THE RESIDENTIAL COMMISSION CONFIGUE--------------
        ResidentialCommissionConfigure__c ResidentialCommissionConfigueRecord = new ResidentialCommissionConfigure__c();
        ResidentialCommissionConfigueRecord.Supplier__c = AccountRecord.Id;
        ResidentialCommissionConfigueRecord.EffectiveFrom__c = EffectiveFrom;
        ResidentialCommissionConfigueRecord.Type__c = 'Type value1';
        ResidentialCommissionConfigueRecord.Flat_Fee_Paid_To_DNE__c = 3324;
        ResidentialCommissionConfigueRecord.PromoCode__c = 'test';
        ResidentialCommissionConfigueRecord.Commodity__c = 'Gas';
        ResidentialCommissionConfigueRecord.Contractsource__c = 'Test Value1';
        ResidentialCommissionConfigueRecord.Term__c = 123;
        ResidentialCommissionConfigueRecord.ProvinceorState__c = 'State test';
        ResidentialCommissionConfigueRecord.Country__c = 'Country test';
        ResidentialCommissionConfigueRecord.ECC__c = true;
        ResidentialCommissionConfigueRecord.Closer__c = 2;
        ResidentialCommissionConfigueRecord.Level1__c = 1;
        ResidentialCommissionConfigueRecord.Level2__c = 2.2;
        ResidentialCommissionConfigueRecord.Level3__c = 3.1;
        ResidentialCommissionConfigueRecord.Level4__c = 4;
        ResidentialCommissionConfigueRecord.Level5__c = 1.2;
        ResidentialCommissionConfigueRecord.Clawbacktime__c = 30;
        Insert ResidentialCommissionConfigueRecord;
        
        //--------CREATING THE RESIDENTIAL COMMISSION HIERARCHY--------------
        Residential_Commission_Hierarchy__c ResidentialCommissionHierarchyRecords = new Residential_Commission_Hierarchy__c();
        ResidentialCommissionHierarchyRecords.Effective_From__c = EffectiveFrom;
        ResidentialCommissionHierarchyRecords.Closer__c = ContactRecord.Id;
        ResidentialCommissionHierarchyRecords.Level1__c = ContactRecord1.Id;
        ResidentialCommissionHierarchyRecords.Level2__c = ContactRecord2.Id;
        ResidentialCommissionHierarchyRecords.Level3__c = ContactRecord3.Id;
        ResidentialCommissionHierarchyRecords.Level4__c = ContactRecord4.Id;
        ResidentialCommissionHierarchyRecords.Level5__c = ContactRecord5.Id;
        Insert ResidentialCommissionHierarchyRecords;
    }
 
 /*********************************************************
	@Name           : createResiOpp
	@Parameters     : 
	@Return type    : Void
	@Description    : Method to create Residential Opportunity & 
					  check Residential Commission when Residential Opportunity is changed to closed won
	********************************************************/    
  
    @isTest 
    static void createResiOpp() 
    {
        createData();
        Test.startTest();
        Residential_Opportunity__c ResidentialOpportunityRecords = new Residential_Opportunity__c();
        ResidentialOpportunityRecords.Closer__c = 'Test Data';
        ResidentialOpportunityRecords.AccountName__c = 'Test Account Data';
        ResidentialOpportunityRecords.Type__c = 'Type value1';
        ResidentialOpportunityRecords.StageName__c = 'Qualification';
        ResidentialOpportunityRecords.PromoCode__c = 'test';
        ResidentialOpportunityRecords.CloseDate__c = system.today();
        ResidentialOpportunityRecords.Commodity__c = 'Gas';
        ResidentialOpportunityRecords.Contractsource__c = 'Test Value1';
        ResidentialOpportunityRecords.Term__c = 123;
        ResidentialOpportunityRecords.Country__c = 'Country test';
        ResidentialOpportunityRecords.State__c = 'State test';
        ResidentialOpportunityRecords.Supplier__c = 'Test Account Data';
        ResidentialOpportunityRecords.ECC__c = true;
        Insert ResidentialOpportunityRecords;
        
        system.assertEquals(1, [Select Id from Residential_Opportunity__c].size());
        
        ResidentialOpportunityRecords.StageName__c = 'Closed Won';
        UPDATE ResidentialOpportunityRecords;
        system.assertEquals('Closed Won', ResidentialOpportunityRecords.StageName__c);
        
        List<Residential_Commission__c> wonOppComm = [Select Id, Paid__c, Amount__c From Residential_Commission__c Where Residential_Opportunity__c =: ResidentialOpportunityRecords.Id ];
        system.assertEquals(6, wonOppComm.size());
       
        wonOppComm[0].Paid__c = True;
        wonOppComm[2].Paid__c = True;
	    UPDATE wonOppComm;
        system.debug('wonOppComm#########>' +wonOppComm);
        
       
        ResidentialOpportunityRecords.StageName__c = 'Cancelled';
        ResidentialOpportunityRecords.Cancelled_Date__c = system.today();
        UPDATE ResidentialOpportunityRecords;
        system.assertEquals('Cancelled', ResidentialOpportunityRecords.StageName__c);
       
       	List<Residential_Commission__c> cancelledOppComm = [Select Id, Paid__c, Amount__c From Residential_Commission__c Where Residential_Opportunity__c =: ResidentialOpportunityRecords.Id ];
        system.assertNotEquals(wonOppComm[0].Amount__c, cancelledOppComm[0].Amount__c);
        
        Test.stopTest();
    }
 
/*********************************************************
	@Name           : createResiOppHieCheck
	@Parameters     : 
	@Return type    : Void
	@Description    : Method to create Residential Opportunity When Closer is not in Hierarchy
					 
	********************************************************/        
    
    @isTest 
    static void createResiOppHieCheck() 
    {
        createData();
        Test.startTest();
        Residential_Opportunity__c ResidentialOpportunityRecords = new Residential_Opportunity__c();
        ResidentialOpportunityRecords.Closer__c = 'Test Contact';
        ResidentialOpportunityRecords.AccountName__c = 'Test Account Data';
        ResidentialOpportunityRecords.Type__c = 'Type value1';
        ResidentialOpportunityRecords.StageName__c = 'Qualification';
        ResidentialOpportunityRecords.PromoCode__c = 'test';
        ResidentialOpportunityRecords.CloseDate__c = system.today();
        ResidentialOpportunityRecords.Commodity__c = 'Gas';
        ResidentialOpportunityRecords.Contractsource__c = 'Test Value1';
        ResidentialOpportunityRecords.Term__c = 123;
        ResidentialOpportunityRecords.Country__c = 'Country test';
        ResidentialOpportunityRecords.State__c = 'State test';
        ResidentialOpportunityRecords.Supplier__c = 'Test Account Data';
        ResidentialOpportunityRecords.ECC__c = true;
        Insert ResidentialOpportunityRecords;
        
        system.assertEquals(1, [Select Id from Residential_Opportunity__c].size());
        
        ResidentialOpportunityRecords.StageName__c = 'Closed Won';
        update ResidentialOpportunityRecords;
        system.assertEquals('Closed Won', ResidentialOpportunityRecords.StageName__c);
        
        List<Residential_Commission__c> wonOppComm = [Select Id, Paid__c, Amount__c From Residential_Commission__c Where Residential_Opportunity__c =: ResidentialOpportunityRecords.Id ];
        system.assertEquals(1, wonOppComm.size());
        wonOppComm[0].Paid__c = True;
	    UPDATE wonOppComm;
        system.debug('wonOppComm#########>' +wonOppComm);
        
        
        ResidentialOpportunityRecords.StageName__c = 'Cancelled';
        ResidentialOpportunityRecords.Cancelled_Date__c = system.today();
        UPDATE ResidentialOpportunityRecords;
        system.assertEquals('Cancelled', ResidentialOpportunityRecords.StageName__c);
        
        List<Residential_Commission__c> cancelledOppComm = [Select Id, Paid__c, Amount__c From Residential_Commission__c Where Residential_Opportunity__c =: ResidentialOpportunityRecords.Id ];
        system.assertNotEquals(wonOppComm[0].Amount__c, cancelledOppComm[0].Amount__c);
        
        Test.stopTest();
    }  
    
    
    /*********************************************************
	@Name           : ResiOppCloseDateNullCheck
	@Parameters     : 
	@Return type    : Void
	@Description    : Method to create Residential Opportunity and 
					  Commission When  Residential Opportunity Close Date is Null
	********************************************************/  
    @isTest 
    static void ResiOppCloseDateNullCheck() 
    {
        createData();
        Test.startTest();
        Residential_Opportunity__c ResidentialOpportunityRecords = new Residential_Opportunity__c();
        ResidentialOpportunityRecords.Closer__c = 'Test Contact';
        ResidentialOpportunityRecords.AccountName__c = 'Test Account Data';
        ResidentialOpportunityRecords.Type__c = 'Type value1';
        ResidentialOpportunityRecords.StageName__c = 'Qualification';
        ResidentialOpportunityRecords.PromoCode__c = 'test';
        //ResidentialOpportunityRecords.CloseDate__c = system.today();
        ResidentialOpportunityRecords.Commodity__c = 'Gas';
        ResidentialOpportunityRecords.Contractsource__c = 'Test Value1';
        ResidentialOpportunityRecords.Term__c = 123;
        ResidentialOpportunityRecords.Country__c = 'Country test';
        ResidentialOpportunityRecords.State__c = 'State test';
        ResidentialOpportunityRecords.Supplier__c = 'Test Account Data';
        ResidentialOpportunityRecords.ECC__c = true;
        Insert ResidentialOpportunityRecords;
        
        system.assertEquals(1, [Select Id from Residential_Opportunity__c].size());
        
        ResidentialOpportunityRecords.StageName__c = 'Closed Won';
        update ResidentialOpportunityRecords;
        system.assertEquals('Closed Won', ResidentialOpportunityRecords.StageName__c);
        
        List<Residential_Commission__c> wonOppComm = [Select Id, Paid__c, Amount__c From Residential_Commission__c Where Residential_Opportunity__c =: ResidentialOpportunityRecords.Id ];
        system.assertEquals(1, wonOppComm.size());
        wonOppComm[0].Paid__c = True;
	    UPDATE wonOppComm;
        system.debug('wonOppComm#########>' +wonOppComm);
        
        
        ResidentialOpportunityRecords.StageName__c = 'Cancelled';
         ResidentialOpportunityRecords.Cancelled_Date__c = system.today();
        UPDATE ResidentialOpportunityRecords;
        system.assertEquals('Cancelled', ResidentialOpportunityRecords.StageName__c);
        
        List<Residential_Commission__c> cancelledOppComm = [Select Id, Paid__c, Amount__c From Residential_Commission__c Where Residential_Opportunity__c =: ResidentialOpportunityRecords.Id ];
        system.assertEquals(wonOppComm[0].Amount__c, cancelledOppComm[0].Amount__c);
        
        Test.stopTest();
    }  
    
    
    /*********************************************************
	@Name           : ClawbackDateExpiryCheck
	@Parameters     : 
	@Return type    : Void
	@Description    : Method to create Residential Opportunity and 
					  Commission When clawback date is expired
	********************************************************/  
    @isTest 
    static void ClawbackDateExpiryCheck() 
    {
        createData();
        Test.startTest();
        Residential_Opportunity__c ResidentialOpportunityRecords = new Residential_Opportunity__c();
        ResidentialOpportunityRecords.Closer__c = 'Test Contact';
        ResidentialOpportunityRecords.AccountName__c = 'Test Account Data';
        ResidentialOpportunityRecords.Type__c = 'Type value1';
        ResidentialOpportunityRecords.StageName__c = 'Qualification';
        ResidentialOpportunityRecords.PromoCode__c = 'test';
        ResidentialOpportunityRecords.CloseDate__c = system.today().addDays(-40);
        ResidentialOpportunityRecords.Commodity__c = 'Gas';
        ResidentialOpportunityRecords.Contractsource__c = 'Test Value1';
        ResidentialOpportunityRecords.Term__c = 123;
        ResidentialOpportunityRecords.Country__c = 'Country test';
        ResidentialOpportunityRecords.State__c = 'State test';
        ResidentialOpportunityRecords.Supplier__c = 'Test Account Data';
        ResidentialOpportunityRecords.ECC__c = true;
        Insert ResidentialOpportunityRecords;
        
        system.assertEquals(1, [Select Id from Residential_Opportunity__c].size());
        
        ResidentialOpportunityRecords.StageName__c = 'Closed Won';
        update ResidentialOpportunityRecords;
        system.assertEquals('Closed Won', ResidentialOpportunityRecords.StageName__c);
        
        List<Residential_Commission__c> wonOppComm = [Select Id, Paid__c, Amount__c From Residential_Commission__c Where Residential_Opportunity__c =: ResidentialOpportunityRecords.Id ];
        system.assertEquals(1, wonOppComm.size());
        wonOppComm[0].Paid__c = True;
	    UPDATE wonOppComm;
        system.debug('wonOppComm#########>' +wonOppComm);
        
        
        ResidentialOpportunityRecords.StageName__c = 'Cancelled';
        ResidentialOpportunityRecords.Cancelled_Date__c = system.today();
        UPDATE ResidentialOpportunityRecords;
        system.assertEquals('Cancelled', ResidentialOpportunityRecords.StageName__c);
        
        List<Residential_Commission__c> cancelledOppComm = [Select Id, Paid__c, Amount__c From Residential_Commission__c Where Residential_Opportunity__c =: ResidentialOpportunityRecords.Id ];
        system.assertEquals(wonOppComm[0].Amount__c, cancelledOppComm[0].Amount__c);
        
        Test.stopTest();
    }  

    
}