force-app/main/default/objects/Opportunity_opener__c/Opportunity_opener__c.object-meta.xml
<CustomObject>
    <label>Opportunity opener closer</label>
    <nameField>
        <label>Opportunity opener  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity opener closer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_opener__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity opener closer (Closer)</relationshipLabel>
    <relationshipName>Opportunity_opener_closer1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_opener__c/fields/Is_Incorrect_Opener__c.field-meta.xml
<CustomField>
    <fullName>Is_Incorrect_Opener__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Incorrect Opener</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_opener__c/fields/Opener__c.field-meta.xml
<CustomField>
    <fullName>Opener__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opener</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity opener closer</relationshipLabel>
    <relationshipName>Opportunity_opener_closer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_opener__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity opener closer</relationshipLabel>
    <relationshipName>Opportunity_opener_closer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FindOpportunityOpenerBatch.cls
/**************************************************
* Class: FindOpportunityOpenerBatch
* Description: Batch class used to find mismatch opener and closer for opportunity
****************************************************/
global class FindOpportunityOpenerBatch implements Database.Batchable<sObject>,Database.Stateful{
    global String query;
    global FindOpportunityOpenerBatch(){
        query = 'SELECT Id,Closer__c,Is_Incorrect_Opener__c,Opener__c,Opportunity__c FROM Opportunity_opener__c';
    }
    // Batch Start Method
    global Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('query = '+query);
        return Database.getQueryLocator(query);
    }
    //Batch Execute Method
    global void execute(Database.BatchableContext BC, List<Opportunity_opener__c> opportunityOpeners){
        System.debug('opportunityOpeners^^' + opportunityOpeners.size());
        if(opportunityOpeners.size() > 0){
            List<Opportunity_opener__c> openersList = new List<Opportunity_opener__c>();
            for(Opportunity_opener__c oppOpeners : opportunityOpeners){
                if(oppOpeners.Opener__c != oppOpeners.Closer__c){
                    oppOpeners.Is_Incorrect_Opener__c = true;
                    openersList.add(oppOpeners);
                }
            }
            System.debug('openersList^^' + openersList.size());
            try{
                if(openersList.size() > 0){
                    UPDATE openersList;
                }
            }catch(Exception ex){
                System.debug('exception occured on updation ^^' + ex.getMessage());
            }
        }
    }
    // finish method
    global void finish(Database.BatchableContext BC) {
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
                            JobItemsProcessed,
                            TotalJobItems
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];
        System.debug('#### job^^' + job);
        System.debug('#### FindOpportunityOpenerBatch Finished.');
    }
}