force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Location Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Address</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Contract_type__c.field-meta.xml
<CustomField>
    <fullName>Contract_type__c</fullName>
    <label>Contract type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Service_Address_As_Parent__c.field-meta.xml
<CustomField>
    <fullName>Service_Address_As_Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Address As Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_Market_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Market_Account_Name__c</fullName>
    <label>Site - Market - Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gas</fullName>
                <default>true</default>
                <label>Gas</label>
            </value>
            <value>
                <fullName>Electricity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>KWh</fullName>
            </value>
            <value>
                <fullName>GJ</fullName>
            </value>
            <value>
                <fullName>MWh</fullName>
            </value>
            <value>
                <fullName>DTH</fullName>
            </value>
            <value>
                <fullName>MCF</fullName>
            </value>
            <value>
                <fullName>M3</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>Therm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MergeUtility.cls
public class MergeUtility {
    
    public static void mergeData(String winningAcctId, List<Id> duplicateAccounts){
        List<Opportunity> opptList = new List<Opportunity>();
        List<Contact> contList = new List<Contact>();
        List<Contract> contractList = new List<Contract>();
        List<SBQQ__Quote__c> quoteList = new List<SBQQ__Quote__c>();
        List<Site__c> siteList = new List<Site__c>();
        List<Site__c> listTobeDelete = new List<Site__c>();
        
        // fetch All Opportunities
        for(Opportunity opp : [SELECT Id,AccountId FROM Opportunity WHERE AccountId IN: duplicateAccounts]){
            opp.AccountId = winningAcctId;
            opptList.add(opp);
        }
        System.debug('opptList^^' + opptList.size());
        
        // Fetch All Contacts
        for(Contact cont : [SELECT Id,AccountId FROM Contact WHERE AccountId IN: duplicateAccounts]){
            cont.AccountId = winningAcctId;
            contList.add(cont);
        }
        System.debug('contList^^' + contList.size());
        
        // Fetch All Sites
        for(Site__c siteRec : [SELECT Id,Contract__c,Contract_type__c,Account__c,Market__c,Opportunity__c,
                               Service_Address_As_Parent__c,Site_Market_Account_Name__c,Name,Type__c,Unit_of_Measure__c,
                               Volume__c FROM Site__c WHERE Account__c IN: duplicateAccounts])
        {
            listTobeDelete.add(siteRec);
            Site__c newSite = new Site__c();
            newSite = siteRec;
            newSite.Account__c = winningAcctId;
            siteList.add(newSite);
        }
        System.debug('siteList^^' + siteList.size());
        System.debug('listTobeDelete^^' + listTobeDelete.size());
        
        // Fetch All Contracts
        for(Contract cont : [SELECT Id,AccountId FROM Contract WHERE AccountId IN: duplicateAccounts])
        {
            cont.AccountId = winningAcctId;
            contractList.add(cont);
        }
        System.debug('contractList^^' + contractList.size());
        // Fetch All Notes
        // Fetch All Files
        // Fetch All Quotes
        for(SBQQ__Quote__c quoteRec : [SELECT Id,SBQQ__Account__c FROM SBQQ__Quote__c WHERE SBQQ__Account__c 
                                       IN: duplicateAccounts])
        {
            quoteRec.SBQQ__Account__c = winningAcctId;
            quoteList.add(quoteRec);   
        }
        System.debug('quoteList^^' + quoteList.size());
        
        try{
            if(opptList.size() > 0){
                UPDATE opptList;
                System.debug('opportunity updated.');
            }
            if(contList.size() > 0){
                UPDATE contList;
                System.debug('contact updated.');
            }
            if(listTobeDelete.size() > 0){
                UPDATE listTobeDelete;
                System.debug('site deleted.');
            }
            if(siteList.size() > 0){
                UPDATE siteList;
                System.debug('site updated.');
            }
            /*if(contractList.size() > 0){
                UPDATE contractList;
                System.debug('contract updated.');
            }*/
            if(quoteList.size() > 0){
                UPDATE quoteList;
                System.debug('quote updated.');
            }
        }catch(Exception ex){
            System.debug('exception occured on merge data^^' + ex.getMessage());
        }
    }
    
}