force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Month_Year__c/Month_Year__c.object-meta.xml
<CustomObject>
    <label>Month Year</label>
    <nameField>
        <label>Months Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Month Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <label>Price List</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_List__c/fields/Currency_ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_ISO_Code__c</fullName>
    <label>Currency ISO Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Effective_From__c</fullName>
    <label>Effective From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Effective_To__c.field-meta.xml
<CustomField>
    <fullName>Effective_To__c</fullName>
    <label>Effective To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Is_Valid__c.field-meta.xml
<CustomField>
    <fullName>Is_Valid__c</fullName>
    <formula>AND(  NOW()   &gt;  Effective_From__c ,  NOW()  &lt;  Effective_To__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Latest__c.field-meta.xml
<CustomField>
    <fullName>Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month-Year</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Month_Year__c.field-meta.xml
<CustomField>
    <fullName>Month_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Month Year</label>
    <referenceTo>Month_Year__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SupplierPricingHistory.cls
/*************************************************************
* Class: SupplierPricingHistory
* Author: Soljit <VW>
* Date: 2019-05-24
* Description: apex class for handle supplier price history
**************************************************************/
public class SupplierPricingHistory{
    public static FINAL Integer RECORDS_PER_PAGE = 100;

	private final Account theAccount;
    public List<Price_List__c> allPrices {get; set;}
    public List<Price_List__c> pricesToShow {get; set;}

    // pagination variables
    public Integer counter = 0;                     //To track the number of records parsed
    public Integer limitSize {get; set;}            //Number of records to be displayed
    public Integer totalSize {get; set;}            //To Store the total number of records available
    public Integer totalPages {get; set;}

    public String summaryMessage {get; set;}

    // ========================================

    public SupplierPricingHistory(ApexPages.StandardController stdController) {
        List<String> fieldsToAdd = new List<String>{'Name'};
        stdController.addFields(fieldsToAdd);
        pricesToShow = new List<Price_List__c>();
        this.theAccount = (Account)stdController.getRecord();
        allPrices = [SELECT Id, Name, Product_Code__c, Type__c, Size__c, Term__c, List_Price__c,
                            Market__c, Currency_ISO_Code__c, Supplier__c,
                            Month__c, Effective_From__c, Effective_To__c, Month_Year__r.Name, Market__r.Name, 
                            Latest__c, Month_Year__c, Is_Valid__c 
                     FROM Price_List__c 
                     WHERE Supplier__c = :theAccount.Id 
                     ORDER BY Latest__c DESC, Is_Valid__c DESC, Month_Year__c ];
        
        if(allPrices.isEmpty())
        {
            String pageMessage = Label.PageMessage_No_Price_History;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, pageMessage));
        }
    
        // Pagination/Navigation --->>>

        limitSize = RECORDS_PER_PAGE;
        totalSize = allPrices.size();

        totalPages = Integer.valueOf(totalSize/limitSize);
        if(Math.mod(totalSize,limitSize)!=0)
          totalPages+=1;

        //if there are more records than the maximum number of records to show on a page, we only display the first batch (max allowed/page)
        if((counter+limitSize) <= totalSize)
        {
            for(Integer i=0;i<limitSize;i++)
            {
                pricesToShow.add(allPrices.get(i));
            }
        }
        //else, all the records will be shown
        else
        {
            pricesToShow.addAll(allPrices);            
        }
        // Pagination/Navigation ---<<<

        // Showing ~totalSize results on ~totalPages page(s), ~limitSize records/page
        summaryMessage = Label.PageMessage_Price_History_Summary.replace('~totalSize', String.valueOf(totalSize));
        summaryMessage = summaryMessage.replace('~totalPages', String.valueOf(totalPages));
        summaryMessage = summaryMessage.replace('~limitSize', String.valueOf(limitSize));
    }
    // ----------------------------------------

    public String getRecordName() 
    {
        return (String)theAccount.get('Name');
    }

    // =======================================================================
    // ======================== Pagination/Navigation ========================
    // =======================================================================

    /*********************************************************************************
    Method Name    : beginning
    Description    : called when the user wants to navigate to the first page of records to show
    Return Type    : void
    Parameter      : none           
    *********************************************************************************/
    public void beginning(){
   
        pricesToShow.clear();
        counter=0;
        // if there are more records than the maximum number of records to show on a page, we only display the first batch (max allowed/page)
        if((counter + limitSize) <= totalSize)
        {       
            for(Integer i=0;i<limitSize;i++)
            {
                pricesToShow.add(allPrices.get(i));
            }           
        } 
    //else, all the records will be shown
        else
        {       
            for(Integer i=0;i<totalSize;i++)
            {
                pricesToShow.add(allPrices.get(i));
            }               
        }
       
    }
   
    /*********************************************************************************
    Method Name    : next
    Description    : called when the user wants to navigate to the next page of records to show
    Return Type    : void
    Parameter      : none           
    *********************************************************************************/
    public void next(){
   
        pricesToShow.clear();
        counter=counter+limitSize;
       
        // if there are more records than the maximum number of records to show on a page, we only display the first batch (max allowed/page)
        if((counter+limitSize) <= totalSize)
        {
            //for(Integer i=counter-1;i<(counter+limitSize);i++){
            for(Integer i=counter;i<(counter+limitSize);i++)
            {
                pricesToShow.add(allPrices.get(i));
            }
        } 
        //else, all the records will be shown
        else
        {
            for(Integer i=counter;i<totalSize;i++)
            {
                pricesToShow.add(allPrices.get(i));
            }
        }
    }
   
    /*********************************************************************************
    Method Name    : previous
    Description    : called when the user wants to navigate to the previous page of records to show
    Return Type    : void
    Parameter      : none           
    *********************************************************************************/
    public void previous(){
   
        pricesToShow.clear();

        counter=counter-limitSize;       
       
        for(Integer i=counter;i<(counter+limitSize); i++)
        {
            pricesToShow.add(allPrices.get(i));
        }
    }

    /*********************************************************************************
    Method Name    : last
    Description    : called when the user wants to navigate to the last page of records to show
    Return Type    : void
    Parameter      : none           
    *********************************************************************************/
    public void last (){
   
        pricesToShow.clear();
       
        if(math.mod(totalSize , limitSize) == 0)
        {
            counter = limitSize * ((totalSize/limitSize)-1);
        } 
        else if (math.mod(totalSize , limitSize) != 0)
        {
            counter = limitSize * ((totalSize/limitSize));
        }
         // all the records in the previous batch will be added to the list of records to show
        //for(Integer i=counter-1;i<totalSize;i++)
        for(Integer i=counter;i<totalSize;i++)
        {
                pricesToShow.add(allPrices.get(i));
        }
        /*for(Integer i=counter-1;i<totalSize-1;i++)
        {
                pricesToShow.add(allPrices.get(i));
        }*/
       
    }
    
    /*********************************************************************************
    Method Name    : getDisableNext
    Description    : used to enable/disable the button "Next"
    Return Type    : Boolean: TRUE if the button stays enabled, otherwise FALSE 
    Parameter      : none           
    *********************************************************************************/
    public Boolean getDisableNext()
    {   
        //if we have reached the last page of records to show, the button "Next" will be disabled
        if((counter + limitSize) >= totalSize )
            return true ;
        // else, it will stay enabled
        else
            return false ;
    }
   
    /*********************************************************************************
    Method Name    : getDisablePrevious
    Description    : used to enable/disable the button "Previous"
    Return Type    : Boolean: TRUE if the button stays enabled, otherwise FALSE 
    Parameter      : none           
    *********************************************************************************/
    public Boolean getDisablePrevious()
    {   
        //if we are on the first page of records to show, the button "Previous" will be disabled
        if(counter == 0)
            return true ;
        // else, it will stay enabled
        else
            return false ;
    } 

    /*********************************************************************************
    Method Name    : getRenderNavigation
    Description    : used to enable/disable the navigation buttons section
    Return Type    : Boolean: TRUE if the section stays enabled, otherwise FALSE 
    Parameter      : none           
    *********************************************************************************/
    public Boolean getRenderNavigation()
    {   
        //if we have less records than the max number of records to display on the page, navigation won't be displayed
        if(limitSize < totalSize)
            return true ;
        else
            return false ;
    }
}