force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Location Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Address</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gas</fullName>
                <default>true</default>
                <label>Gas</label>
            </value>
            <value>
                <fullName>Electricity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>KWh</fullName>
            </value>
            <value>
                <fullName>GJ</fullName>
            </value>
            <value>
                <fullName>MWh</fullName>
            </value>
            <value>
                <fullName>DTH</fullName>
            </value>
            <value>
                <fullName>MCF</fullName>
            </value>
            <value>
                <fullName>M3</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>Therm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PriceChartTreeViewController.cls
public class PriceChartTreeViewController {

    public static Id recordId;
    public static String selectedMarket;
    public String sObjectName{get;set;}
    Set<Id> accountIds;
    List<Account> selecAccList ;
    
    public Map<Id,TreeWrapper> addressSiteMap {get;set;} 
    
    public String jsonDataForAddressSite {get;set;}
    
    public PriceChartTreeViewController(){
        //recordId = parentID ; 
         recordId = '0010q00000DRz0FAAT' ;
        //selectedMarket = market;
        selectedMarket = 'Alberta';
        
         addressSiteMap = new Map<Id,TreeWrapper>();
        TreeWrapper treewrp ;
        
        for(Account addressAccount: [Select Id, name,ParentId,BillingState,Total_Annual_Volume_ElectrictIy__c,Total_Annual_Volume_Gas__c,
                                     Market__r.Name from Account 
                                     where parentId=:recordId 
                                    ] ){
            treewrp = new TreeWrapper(recordId,addressAccount) ;  
            addressSiteMap.put(addressAccount.Id,treewrp);                            
        } 
        
        System.debug('addressSiteMap=='+addressSiteMap);
        
        for(Site__c site:[Select Id, name,Market__c,Volume__c,Type__c , Unit_of_Measure__c ,Account__c 
                                     from Site__c where Account__c IN:addressSiteMap.keySet()]){
            addressSiteMap.get(site.Account__c).addSite(site);
        }
        
        System.debug('addressSiteMap=='+addressSiteMap);
        
        jsonDataForAddressSite= JSON.serialize(addressSiteMap);
        
    }
    
    @AuraEnabled
    
    public static List<Account> getAccountListByOpportunity(ID parentID , Id market){
        
        recordId =parentID ; 
        selectedMarket = market;
        List<Account> accountList = [Select Id, name,ParentId,BillingState,Total_Annual_Volume_ElectrictIy__c,Total_Annual_Volume_Gas__c,
                                     Market__r.Name from Account 
                                     where parentId=:recordId AND Market__c =:selectedMarket
                                      ] ; 
        
        return accountList ;
        
        
    }
    
    public class TreeWrapper{
        
        public String parentAccountId {get;set;}
        public Account parentAccountDetail {get;set;}
        public Account addressAccount {get;set;}
        public List<Site__c> siteList {get;set;}
        
        public TreeWrapper(String parentId){
            this.parentAccountId = parentId;
            this.addressAccount = new Account();
            this.siteList = new List<Site__c>();
            this.parentAccountDetail = [Select Id, Name from Account where Id=: parentId] ;
        }
        
        public TreeWrapper(String parentId, Account acc){
            this.parentAccountId = parentId;
            this.addressAccount = acc;
            this.siteList = new List<Site__c>();
            this.parentAccountDetail = [Select Id, Name from Account where Id=: parentId] ;
        }
        
        public void addSite(Site__c site){
            this.siteList.add(site);
        }
	        
    }
    
    
    @AuraEnabled
    
    public static List<Site__c> getSiteList(ID parentID, String market, String selectedType){
        
        
        //parentID ='0010q00000MnBlzAAF' ;
        
        List<Site__c> siteList = [Select Id, name,Market__c,Volume__c,Type__c , Unit_of_Measure__c  
                                     from Site__c where Account__c =:parentID And Type__c =:selectedType ] ; 
        
        return siteList ;
        
        
    } 
    
    
}