force-app/main/default/objects/Residential_Commission_Hierarchy__c/Residential_Commission_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Residential Commission Hierarchy</label>
    <nameField>
        <label>Residential Commission Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Commission hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Residential_Commission_Hierarchy__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residential Commission hierarchies (Closer)</relationshipLabel>
    <relationshipName>Residential_Commission_hierarchiesF3PS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Residential_Commission_Hierarchy__c/fields/Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Effective_From__c</fullName>
    <label>Effective From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Residential_Commission_Hierarchy__c/fields/Opener__c.field-meta.xml
<CustomField>
    <fullName>Opener__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opener</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residential Commission hierarchies (Opener)</relationshipLabel>
    <relationshipName>Residential_Commission_hierarchiesEk3B</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Residential_Opportunity__c/Residential_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Residential Opportunity</label>
    <nameField>
        <label>Residential Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Opportunity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Residential_Opportunity__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <label>Commodity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Electricity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Residential_Opportunity__c/fields/ContractSource__c.field-meta.xml
<CustomField>
    <fullName>ContractSource__c</fullName>
    <label>Contract Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Residential_Opportunity__c/fields/ECC__c.field-meta.xml
<CustomField>
    <fullName>ECC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ECC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Residential_Opportunity__c/fields/Opener__c.field-meta.xml
<CustomField>
    <fullName>Opener__c</fullName>
    <label>Opener</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Residential_Opportunity__c/fields/ResidentialCommissionConfigure__c.field-meta.xml
<CustomField>
    <fullName>ResidentialCommissionConfigure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Commission Configure</label>
    <referenceTo>ResidentialCommissionConfigure__c</referenceTo>
    <relationshipLabel>Residential Opportunity</relationshipLabel>
    <relationshipName>Residential_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Residential_Opportunity__c/fields/ResidentialCommissionHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ResidentialCommissionHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residential Commission Hierarchy</label>
    <referenceTo>Residential_Commission_Hierarchy__c</referenceTo>
    <relationshipLabel>Residential Opportunity</relationshipLabel>
    <relationshipName>Residential_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/ResidentialCommissionConfigure__c.object-meta.xml
<CustomObject>
    <label>Residential Commission Configure</label>
    <nameField>
        <label>Residential Commission Configure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Commissions Configure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <label>Closer Commission Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Contractsource__c.field-meta.xml
<CustomField>
    <fullName>Contractsource__c</fullName>
    <label>Contract Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/ECC__c.field-meta.xml
<CustomField>
    <fullName>ECC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ECC (Yes or No)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/EffectiveFrom__c.field-meta.xml
<CustomField>
    <fullName>EffectiveFrom__c</fullName>
    <label>Effective From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Opener__c.field-meta.xml
<CustomField>
    <fullName>Opener__c</fullName>
    <label>Opener Commission Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/ProvinceorState__c.field-meta.xml
<CustomField>
    <fullName>ProvinceorState__c</fullName>
    <label>Province or State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Residential Commissions Configure</relationshipLabel>
    <relationshipName>Residential_Commissions_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ResidentialCommissionConfigure__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResidentialUtility.cls
/**************************************************
* Class: ResidentialUtility
* Author: Soljit <VW>
* Date: 2019-11-25
* Description: ResidentialUtility
****************************************************/
public class ResidentialUtility {
    
    /*********************************************************
	@Name           : populateResidentialCommissionConfigure
	@Parameters     : List of new Residential Opportunity
	@Reutrn type    : void
	@Description    : Populate Residential Commission Configure
	********************************************************/
   Public static void populateResidentialCommissionConfigure(List<Residential_Opportunity__c> resOppList){
        System.debug('calling populateResidentialCommissionConfigure()');
                
        Map<String,ResidentialCommissionConfigure__c> commissionConfigureMap = createCommissionConfigureMap();
        if(commissionConfigureMap.isEmpty()){
            return;            
        }            
        for(Residential_Opportunity__c resiOpp : resOppList)
        {
            if(resiOpp.ResidentialCommissionConfigure__c == null){
                String Key = resiOpp.PromoCode__c + resiOpp.Supplier__c + resiOpp.Commodity__c + resiOpp.ContractSource__c + resiOpp.Term__c + resiOpp.State__c + resiOpp.Country__c + resiOpp.ECC__c + resiOpp.Type__c;
                System.debug('resiOpp Key ::: ' + Key);
                if(commissionConfigureMap.containsKey(Key)){
                    resiOpp.ResidentialCommissionConfigure__c = commissionConfigureMap.get(Key).Id;
                }
            }             
        }
        System.debug('### After Commission Configure oppList.size() ::: ' + resOppList.size());
        System.debug('### After Commission Configure oppList ::: ' + resOppList);        
    }
       
    /*********************************************************
	@Name 			: populateResidentialCommissionHierarchy
	@Parameters 	: List of new Residential Opportunity
	@Reutrn type 	: void
	@Description 	: To populate commission Hierarchy
	********************************************************/
    public static void populateResidentialCommissionHierarchy(List<Residential_Opportunity__c> resiOppList){
        System.debug('calling populateResidentialCommissionHierarchy()');
        System.debug('resiOppList.size() ::: ' + resiOppList.size());
        System.debug('resiOppList ::: ' + resiOppList);
        Set<String> closerSet = new Set<String>();
        for(Residential_Opportunity__c resiOpp : resiOppList)
        {		
            if(resiOpp.Closer__c != null)
            {
                closerSet.add(resiOpp.Closer__c);
            }
        }
        System.debug('closerSet.size() ::: ' + closerSet.size());
        System.debug('closerSet ::: ' + closerSet);
        if(closerSet.isEmpty())
        {
            System.debug('ResidentialUtility.populateResidentialCommissionHierarchy() - NO CLOSER WAS FOUND for these Opportunities.');
            return;
        }
        
        Datetime todayDateTime = Datetime.now();
        
        List<Residential_Commission_Hierarchy__c> commissionHierarchyList = [SELECT Id, Closer__c,Closer__r.Name 
                                                                             FROM Residential_Commission_Hierarchy__c
                                                                             WHERE Closer__r.Name IN :closerSet
                                                                             AND Effective_From__c < :todayDateTime
                                                                             ORDER BY Effective_From__c DESC];
        
        System.debug('commissionHierarchyList = ' + commissionHierarchyList);
        
        if(commissionHierarchyList.isEmpty())
        {
            System.debug('ERROR in ResidentialUtility.populateResidentialCommissionHierarchy() - no Commission Hierarchy found.');
            return;
        }
        
        // the key = Opener__c (ex: 0030q00000OYa8h)
        Map<String, Residential_Commission_Hierarchy__c> commissionHierarchyMap = new Map<String, Residential_Commission_Hierarchy__c>();
        
        for(Residential_Commission_Hierarchy__c commHier : commissionHierarchyList)
        {
            String theKey = commHier.Closer__r.Name;
            if(!commissionHierarchyMap.containsKey(theKey))
            {
                commissionHierarchyMap.put(theKey, commHier);
            }
        }
        System.debug('commissionHierarchyMap.size() ::: ' + commissionHierarchyMap.size());        
        System.debug('commissionHierarchyMap ::: ' + commissionHierarchyMap);        
        
        for(Residential_Opportunity__c resiOpp : resiOppList)
        {            
            System.debug('Opportunity = ' + resiOpp);
            if(resiOpp.ResidentialCommissionHierarchy__c == null){
                String opportunityKey = resiOpp.Closer__c;
                
                System.debug('opportunityKey = ' + opportunityKey);
                
                Residential_Commission_Hierarchy__c relatedCommHier = commissionHierarchyMap.get(opportunityKey);
                
                System.debug('relatedCommHier = ' + relatedCommHier);
                
                if(relatedCommHier==null)
                {
                    String errorMessage = 'Please create a Commission Hierarchy record for this CLOSER (' + resiOpp.Closer__c + ')';
                    System.debug('ERROR : ' + errorMessage);
                }
                else
                {
                    resiOpp.ResidentialCommissionHierarchy__c = relatedCommHier.Id;
                }                
            }
        }
        System.debug('After Commission Hierarchy resiOppList.size() = ' + resiOppList.size());        
        System.debug('After Commission Hierarchy resiOppList = ' + resiOppList);        
    }
    
    /*********************************************************
	@Name 			: createCommissionConfigureMap
	@Parameters 	: Boolean (If want to use all commission configure record give true as parameter otherwise false)
	@Reutrn type 	: void
	@Description 	: create commission Configure
	********************************************************/
    public static Map<String,ResidentialCommissionConfigure__c> createCommissionConfigureMap(){
        Map<String,ResidentialCommissionConfigure__c> commissionConfigureMap = new Map<String,ResidentialCommissionConfigure__c>();        
        Datetime dateTimeNow = Datetime.now();
        
        for(ResidentialCommissionConfigure__c commConfigure : [SELECT Id,PromoCode__c,Supplier__c,Supplier__r.Name,
                                                               Commodity__c,Contractsource__c,Term__c,ProvinceorState__c,
                                                               Country__c,ECC__c,Type__c,EffectiveFrom__c 
                                                               FROM ResidentialCommissionConfigure__c 
                                                               WHERE EffectiveFrom__c < :dateTimeNow 
                                                               ORDER BY EffectiveFrom__c DESC])
        {
            // CommissionType
            String theKey = commConfigure.PromoCode__c + commConfigure.Supplier__r.Name + commConfigure.Commodity__c + commConfigure.Contractsource__c + commConfigure.Term__c + commConfigure.ProvinceorState__c + commConfigure.Country__c + commConfigure.ECC__c + commConfigure.Type__c;
            if(!commissionConfigureMap.containsKey(theKey))
            {
                commissionConfigureMap.put(theKey,commConfigure);
            }
        }
        System.debug('commissionPercentMap = ' + commissionConfigureMap);
        return commissionConfigureMap;
    }
}