force-app/main/default/objects/Opportunity_Data_Temp__c/Opportunity_Data_Temp__c.object-meta.xml
<CustomObject>
    <label>Opportunity Data Temp</label>
    <nameField>
        <label>Opportunity Data Temp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Data Temp</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Data_Temp__c/fields/Adder__c.field-meta.xml
<CustomField>
    <fullName>Adder__c</fullName>
    <label>Adder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Data_Temp__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Data Temp</relationshipLabel>
    <relationshipName>Opportunity_Data_Temp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Data_Temp__c/fields/Contract_Price__c.field-meta.xml
<CustomField>
    <fullName>Contract_Price__c</fullName>
    <label>Contract Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Data_Temp__c/fields/Elec_Volume__c.field-meta.xml
<CustomField>
    <fullName>Elec_Volume__c</fullName>
    <label>Elec Volume</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Data_Temp__c/fields/Gas_Volume__c.field-meta.xml
<CustomField>
    <fullName>Gas_Volume__c</fullName>
    <label>Gas Volume</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Data_Temp__c/fields/Is_Opener_Closer_MisMatch__c.field-meta.xml
<CustomField>
    <fullName>Is_Opener_Closer_MisMatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Opener Closer MisMatch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Data_Temp__c/fields/IsAgainProceed__c.field-meta.xml
<CustomField>
    <fullName>IsAgainProceed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsAgainProceed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Data_Temp__c/fields/Opener__c.field-meta.xml
<CustomField>
    <fullName>Opener__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opener</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Data Temp (Opener)</relationshipLabel>
    <relationshipName>Opportunity_Data_Temp1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Data_Temp__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Data Temp</relationshipLabel>
    <relationshipName>Opportunity_Data_Temp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Data_Temp__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Data_Temp__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityDataBatchClass.cls
global class OpportunityDataBatchClass implements Database.Batchable<sObject> {    
    global String query;
    global string RecordId;
    global OpportunityDataBatchClass(String RecId){
        RecordId = RecId;
        query = 'SELECT Id, Name, Adder__c, Company_Name__c,IsAgainProceed__c, Contract_Price__c, Closer__c, Elec_Volume__c, End_Date__c, Gas_Volume__c, Opportunity_Name__c, Start_Date__c, Supplier__c, Opener__c, Type__c, Term__c, Unit__c FROM Opportunity_Data_Temp__c WHERE ID=: RecordId';
    }
    global OpportunityDataBatchClass(){
        query = 'SELECT Id, Name, Adder__c, Company_Name__c,IsAgainProceed__c, Contract_Price__c, Closer__c, Elec_Volume__c, End_Date__c, Gas_Volume__c, Opportunity_Name__c, Start_Date__c, Supplier__c, Opener__c, Type__c, Term__c, Unit__c FROM Opportunity_Data_Temp__c';
    }
   global Database.QueryLocator start(Database.BatchableContext BC) {
       return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, List<Opportunity_Data_Temp__c> tempOppList){
        System.debug('tempOppList^^' + tempOppList.size());
        if(tempOppList.size() > 0){
            Set<String> oppNameSet = new Set<String>();
            Set<Id> opportunityIds = new Set<Id>();
            string ContType;
            Map<string,Opportunity_Data_Temp__c> opportunityTempToBeUpdate = new Map<string,Opportunity_Data_Temp__c>();
            Map<String,Set<String>> oppNameIdMap = new Map<String,Set<String>>();
            Map<String,List<Contract>> contractMap = new Map<String,List<Contract>>();
            for(Opportunity_Data_Temp__c tempData : tempOppList){
                String oppName = tempData.Opportunity_Name__c.toUppercase();
                oppNameSet.add(oppName);
                
            }
            System.debug('oppNameSet^^' + oppNameSet.size());
            System.debug('oppName^^' + oppNameSet);
            if(oppNameSet.size() > 0){
                for(Opportunity opp : [SELECT Id,Name FROM Opportunity WHERE Name IN: oppNameSet]){
                    String oppName = opp.Name.toUppercase();
                    opportunityIds.add(opp.Id);
                    if(!oppNameIdMap.containsKey(oppName)){
                        
                        oppNameIdMap.put(oppName, new Set<String>());
                    }
                    oppNameIdMap.get(oppName).add(opp.Id);
                }
                system.debug('oppNameIdMap^^'+oppNameIdMap);
                if(opportunityIds.size() > 0){
                    for(Contract cont : [SELECT Id,Type__c,Opportunity_Commodity_Type__c,supplier_s_contract_ID__c,SBQQ__Opportunity__c,SBQQ__Opportunity__r.Name,StartDate,EndDate,ContractTerm,
                                         Adder_Margin__c,Selling_Price__c FROM Contract WHERE SBQQ__Opportunity__c IN: opportunityIds order by supplier_s_contract_ID__c asc])
                    {
                        
                        if(!contractMap.containsKey(cont.SBQQ__Opportunity__c))
                        {
                            contractMap.put(cont.SBQQ__Opportunity__c,new List<Contract>());    
                        }
                        contractMap.get(cont.SBQQ__Opportunity__c).add(cont);
                    }
                    System.debug('contractMap^^' + contractMap.size());
                    System.debug('contracts^^' + contractMap);
                    system.debug('tempOppListSize'+tempOppList.size());
                    for(Opportunity_Data_Temp__c tempData : tempOppList){
                        string TempOppType = tempData.Type__c.substring(0,3);
                        String oppName = tempData.Opportunity_Name__c.toUppercase();
                        if(oppNameIdMap.containsKey(oppName)){
                        for(String oppId : oppNameIdMap.get(oppName))
                        {
                            if(contractMap.containsKey(oppId)){
                                for(Contract cont : contractMap.get(oppId)){
                                    ContType = cont.Opportunity_Commodity_Type__c.substring(0,3);
                                    Date ThirtyStartDayAhead = tempData.Start_Date__c.addDays(-30);
                                    Date ThirtyEndDayAhead = tempData.End_Date__c.addDays(-30);
                                    if(cont.StartDate <= tempData.Start_Date__c && cont.StartDate >= ThirtyStartDayAhead 
                                       && cont.EndDate <= tempData.End_Date__c && cont.EndDate >= ThirtyEndDayAhead 
                                       && ContType  == TempOppType 
                                       && cont.ContractTerm == tempData.Term__c 
                                       //&& cont.Adder_Margin__c == tempData.Adder__c 
                                       && cont.Selling_Price__c == tempData.Contract_Price__c)
                                    {
                                        tempData.Opportunity__c = cont.SBQQ__Opportunity__c;
                                        opportunityTempToBeUpdate.put(tempData.Id,tempData);
                                    }
                                }
                            }
                        }
                    }
                    }
                    System.debug('opportunityToBe^^' + opportunityTempToBeUpdate);
                    System.debug('opportunityToBeUpdate^^' + opportunityTempToBeUpdate.size());
                    try{
                        if(opportunityTempToBeUpdate.size() > 0){
                            UPDATE opportunityTempToBeUpdate.Values();
                        }
                        List<Opportunity_Data_Temp__c> OppTempList = new List<Opportunity_Data_Temp__c>();
                        For(Opportunity_Data_Temp__c oppData: [SELECT Id, Closer__c,Is_Opener_Closer_MisMatch__c,IsAgainProceed__c, Opener__c, Opportunity__c,Opportunity__r.Opener__c, Opportunity__r.Closer__c FROM Opportunity_Data_Temp__c where id IN: opportunityTempToBeUpdate.keyset()]){
                            if(oppData.Opportunity__c != null
                               && oppData.Opener__c != oppData.Opportunity__r.Opener__c 
                               || oppData.Closer__c != oppData.Opportunity__r.Closer__c){
                                   oppData.Is_Opener_Closer_MisMatch__c = true;
                                   oppData.IsAgainProceed__c = true;
                                   OppTempList.add(oppData); 
                               }
                        }
                        if(OppTempList.size()>0){
                            UPDATE OppTempList;
                            system.debug('OppTempList'+OppTempList);
                        }
                    }catch(Exception ex){
                        System.debug('exception occured^^' + ex.getMessage());
                    }
                }
            }
        }  
        
    }    
    global void finish(Database.BatchableContext bc){
        
    }    
}