force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Revenue</label>
    <nameField>
        <displayFormat>Revenue-{000}</displayFormat>
        <label>Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Expected_Adder__c.field-meta.xml
<CustomField>
    <fullName>Expected_Adder__c</fullName>
    <label>Expected Adder</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Expected_Volume__c.field-meta.xml
<CustomField>
    <fullName>Expected_Volume__c</fullName>
    <label>Expected Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <label>Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Not Received</fullName>
                <default>true</default>
                <label>Payment Not Received</label>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Volume less than expected</fullName>
            </value>
            <value>
                <fullName>Volume higher than expected</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
            <value>
                <fullName>Revenue is greater than expected</fullName>
            </value>
            <value>
                <fullName>Revenue is less than expected</fullName>
            </value>
            <value>
                <fullName>Fee is greater than expected</fullName>
            </value>
            <value>
                <fullName>Fee is less than expected</fullName>
            </value>
            <value>
                <fullName>Site Drop not approved</fullName>
            </value>
            <value>
                <fullName>Adder less than expected</fullName>
                <isActive>false</isActive>
                <label>Adder less than expected</label>
            </value>
            <value>
                <fullName>Adder more than expected</fullName>
                <isActive>false</isActive>
                <label>Adder more than expected</label>
            </value>
            <value>
                <fullName>Amount greater than expected</fullName>
                <isActive>false</isActive>
                <label>Amount greater than expected</label>
            </value>
            <value>
                <fullName>Amount less than expected</fullName>
                <isActive>false</isActive>
                <label>Amount less than expected</label>
            </value>
            <value>
                <fullName>Canceled not approved</fullName>
                <isActive>false</isActive>
                <label>Canceled not approved</label>
            </value>
            <value>
                <fullName>Missing Site</fullName>
                <isActive>false</isActive>
                <label>Missing Site</label>
            </value>
            <value>
                <fullName>Payment Greater Than Exp. Amount Exceed Error Margin</fullName>
                <isActive>false</isActive>
                <label>Payment Greater Than Exp. Amount Exceed Error Margin</label>
            </value>
            <value>
                <fullName>Payment Greater Than Exp. Amount Within Error Margin</fullName>
                <isActive>false</isActive>
                <label>Payment Greater Than Exp. Amount Within Error Margin</label>
            </value>
            <value>
                <fullName>Payment Less Than Exp. Amount Exceed Error Margin</fullName>
                <isActive>false</isActive>
                <label>Payment Less Than Exp. Amount Exceed Error Margin</label>
            </value>
            <value>
                <fullName>Payment Less Than Exp. Amount Within Error Margin</fullName>
                <isActive>false</isActive>
                <label>Payment Less Than Exp. Amount Within Error Margin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field used for checking invoice at least paid once or not.</description>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Received_Adder__c.field-meta.xml
<CustomField>
    <fullName>Received_Adder__c</fullName>
    <label>Received Adder</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Received_Volume__c.field-meta.xml
<CustomField>
    <fullName>Received_Volume__c</fullName>
    <label>Received Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RevenueTriggerHandler.cls
/*************************************************************
* Class: RevenueTriggerHandler
* Author: Soljit <VW>
* Date: 2019-12-23
* Description: handler class for Invoice__c trigger
**************************************************************/
public class RevenueTriggerHandler {
/*************************************************************
* Method Name : updateRevenuePaymentStatus
* Parameter   : List<Invoice__c> invList
* Description : method used to update Revenue Payment Status
**************************************************************/
    public static void updateRevenuePaymentStatus(List<Invoice__c> invList){
        System.debug('invList.size() ::: ' + invList.size());
        System.debug('invList ::: ' + invList);
        Set<Id> subscriptionIdSet = new Set<Id>();
        for(Invoice__c inv : invList){
            if(inv.Subscription__c != null){
                subscriptionIdSet.add(inv.Subscription__c);   
            }            
        }
        
        Map<Id,SBQQ__Subscription__c> subscriptionIdMap = new Map<Id,SBQQ__Subscription__c>([Select id, Received_Adder__c, Received_Volume__c, Error_Message__c 
                                                                                             from SBQQ__Subscription__c 
                                                                                             where id IN : subscriptionIdSet]);
        System.debug('subscriptionIdMap.size() ::: ' + subscriptionIdMap.size());
        System.debug('subscriptionIdMap. ::: ' + subscriptionIdMap);
        for(Invoice__c invObj : invList){
            invObj.Processed__c = True;                        
            if(invObj.Received_Amount__c < invObj.Amount__c){
                invObj.Flag__c = ConstantString.INVOICE_LESS_AMOUNT;
                if(subscriptionIdMap.containsKey(invObj.Subscription__c)){
                    subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c = invObj.Flag__c;                    
                }
            }
            else if(invObj.Received_Amount__c > invObj.Amount__c){
                invObj.Flag__c = ConstantString.INVOICE_GREATER_AMOUNT; 
                if(subscriptionIdMap.containsKey(invObj.Subscription__c) &&  subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_LESS_AMOUNT){
                    subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c = invObj.Flag__c;                    
                }
            }
            else{
                invObj.Flag__c = ConstantString.INVOICE_RECEIVED_PAYMENT;
                if(subscriptionIdMap.containsKey(invObj.Subscription__c) &&  subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_LESS_AMOUNT && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_GREATER_AMOUNT){
                    subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c = invObj.Flag__c;
                }                            
                if(invObj.Received_Adder__c < invObj.Expected_Adder__c){
                    invObj.Flag__c = ConstantString.INVOICE_LESS_ADDER;                                
                    if(subscriptionIdMap.containsKey(invObj.Subscription__c) && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_LESS_AMOUNT && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_GREATER_AMOUNT){
                        subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c = invObj.Flag__c;
                    }                            
                }
                else if(invObj.Received_Adder__c > invObj.Expected_Adder__c){
                    invObj.Flag__c = ConstantString.INVOICE_GREATER_ADDER; 
                    if(subscriptionIdMap.containsKey(invObj.Subscription__c) && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_LESS_AMOUNT && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_GREATER_AMOUNT && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_LESS_ADDER){
                        subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c = invObj.Flag__c;
                    }                            
                }
                else if(invObj.Received_Volume__c < invObj.Expected_Volume__c){
                    invObj.Flag__c = ConstantString.INVOICE_LESS_VOLUME; 
                    if(subscriptionIdMap.containsKey(invObj.Subscription__c) && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_LESS_AMOUNT && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_GREATER_AMOUNT && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_LESS_ADDER && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_GREATER_ADDER){
                        subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c = invObj.Flag__c;
                    }                            
                }
                else if(invObj.Received_Volume__c > invObj.Expected_Volume__c){
                    invObj.Flag__c = ConstantString.INVOICE_GREATER_VOLUME;
                    if(subscriptionIdMap.containsKey(invObj.Subscription__c) && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_LESS_AMOUNT && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_GREATER_AMOUNT && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_LESS_ADDER && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_GREATER_ADDER && subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c != ConstantString.INVOICE_LESS_VOLUME){
                        subscriptionIdMap.get(invObj.Subscription__c).Error_Message__c = invObj.Flag__c;
                    }                            
                } 
            }                                                                    
        }
        if(subscriptionIdMap.values().size() > 0){
            update subscriptionIdMap.values();
            System.debug('Subscriptions Status Updated successfully.');
        }        
    }
    /*************************************************************
* Method Name : updateCancelledRevenue
* Parameter   : List<Invoice__c> invList
* Description : method used to update flag for invoices
**************************************************************/
    public static void updateCancelledRevenue(List<Invoice__c> invList){
        for (Invoice__c inv : invList){
           inv.Flag__c = 'Payment not received'; 
        } 
    }
}