force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Revenue</label>
    <nameField>
        <displayFormat>Revenue-{000}</displayFormat>
        <label>Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Received_Adder__c.field-meta.xml
<CustomField>
    <fullName>Received_Adder__c</fullName>
    <label>Received Adder</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Received_Volume__c.field-meta.xml
<CustomField>
    <fullName>Received_Volume__c</fullName>
    <label>Received Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Entries__c/Invoice_Entries__c.object-meta.xml
<CustomObject>
    <label>Invoice Entry</label>
    <nameField>
        <displayFormat>IE-{000}</displayFormat>
        <label>Invoice Entries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Entries__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Entries</relationshipLabel>
    <relationshipName>Invoice_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Entries__c/fields/Received_Adder__c.field-meta.xml
<CustomField>
    <fullName>Received_Adder__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Adder</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Entries__c/fields/Received_Volume__c.field-meta.xml
<CustomField>
    <fullName>Received_Volume__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InvoiceEntriesTriggerHandler.cls
/******************************************************************
Name    : InvoiceEntriesTriggerHandler
Author  : Soljit <VW>
Description : Handler class for Invoice_Entries__c trigger to update invoice data
******************************************************************/
public class InvoiceEntriesTriggerHandler {
    /******************************************************************
Method Name    : updateInvoice
Parameter      : List<Invoice_Entries__c> invoiceEntrList
Description    : method for update invoice csv data
******************************************************************/
    public static void updateInvoice (List<Invoice_Entries__c> invoiceEntrList){
        List<Invoice__c> listUpdateInvoice = new List<Invoice__c>();
        for(Invoice_Entries__c innEt : invoiceEntrList){
            if(innEt.Invoice__c !=null){
                Invoice__c inv = new Invoice__c();
                inv.Id = innEt.Invoice__c;
                inv.Received_Amount__c = innEt.Amount__c;
                inv.Received_Adder__c = innEt.Received_Adder__c;
                inv.Received_Volume__c = innEt.Received_Volume__c;
                listUpdateInvoice.add(inv); 
            }
        } 
        System.debug('listUpdateInvoice::'+listUpdateInvoice);
        if(listUpdateInvoice.size() > 0){
            Update listUpdateInvoice;
            System.debug('Update invoices from Invoice Entries::'+listUpdateInvoice.size());
        }
    }
    
}