force-app/main/default/objects/Assumption__c/Assumption__c.object-meta.xml
<CustomObject>
    <label>Assumption</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assumption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assumptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assumption__c/fields/Assumption_Key__c.field-meta.xml
<CustomField>
    <fullName>Assumption_Key__c</fullName>
    <formula>Market__c &amp; &apos;~&apos; &amp; Supplier__c &amp; &apos;~&apos; &amp; TEXT(Commodity__c) &amp; &apos;~&apos; &amp; TEXT(Business_Size__c) &amp; &apos;~&apos; &amp; TEXT(Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assumption Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Business_Size__c.field-meta.xml
<CustomField>
    <fullName>Business_Size__c</fullName>
    <label>Business Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <label>Commodity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commodities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Assumptions</relationshipLabel>
    <relationshipName>Assumptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Pricing_Type__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Type__c</fullName>
    <label>Pricing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is not a supplier</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assumptions</relationshipLabel>
    <relationshipName>Assumptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Margin Min</fullName>
            </value>
            <value>
                <fullName>Margin Max</fullName>
            </value>
            <value>
                <fullName>DNE Admin Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssumptionTriggerHandler.cls
/**************************************************
* Class: AssumptionTriggerHandler
* Author: Soljit <VW>
* Date: 2019-06-12
* Description: AssumptionTriggerHandler for AssumptionTrigger
****************************************************/
public class AssumptionTriggerHandler {
    /**************************************************
* Method Name : checkStatusLead
* Parameters  : List<Assumption__c> assumptionList
* Description : method to check lead status
****************************************************/
    public static void checkStatusLead(List<Assumption__c> assumptionList){
        String assumpKey;
        String assumpMapKey;
        Set<String> suppliers = new Set<String>();
        Set<String> commodities = new Set<String>();
        Set<String> markets = new Set<String>();
        Set<String> updateRecords = new Set<String>();
        Map<String,Assumption__c> assumMap = new Map<String,Assumption__c>();   
        List<String> assumptionKeyList = new List<String>();
        
        // Interate inserted/updated records to make a identical key
        for(Assumption__c assump : assumptionList){
            assumptionKeyList.add(assumpKey);
            suppliers.add(assump.Supplier__c);
            commodities.add(assump.Commodity__c);
            markets.add(assump.Market__c);
            if(assump.Id <> Null){
                updateRecords.add(assump.Id);
            }
        }
        // Fetch relivant records from database
        for(Assumption__c assump : [Select Id, Market__c ,Supplier__c,Assumption_Key__c,Commodity__c,
                                    Business_Size__c,Type__c,Pricing_Type__c,Name
                                    From Assumption__c 
                                    Where Active__c = true AND Market__c IN : markets
                                    AND Supplier__c IN : suppliers AND ID Not IN: updateRecords
                                    AND Commodity__c IN : commodities]){
                                        assumpMapKey = assump.Market__c + '~' + assump.Supplier__c + '~' + assump.Commodity__c + '~' + assump.Business_Size__c + '~' + assump.Type__c + '~' + assump.Pricing_Type__c;
                                        assumMap.put(assumpMapKey, assump);
                                    }
        // Check the record exist in database
        for(Assumption__c assump : assumptionList){
            assumpKey = assump.Market__c + '~' + assump.Supplier__c + '~' + assump.Commodity__c + '~' + assump.Business_Size__c + '~' + assump.Type__c + '~' + assump.Pricing_Type__c;
            if(assump.Active__c && assumMap.containsKey(assumpKey)){ // Check for exiting when insert
                assump.addError(System.Label.Identical_Record_Error_Label  + assumMap.get(assumpKey).Id + ' Record Number : ' + assumMap.get(assumpKey).Name);
            }
        }       
    } 
}